version: "3.9"
services:
  journal:
    build: .
    ports:
      - "5000:5000"
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
    - ./website/database.db:/website/database.db